CREATE SEQUENCE  "ACTIVE_CONF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ACTIVE_OWER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ACT_MODEL_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "AMOUNT_RANGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "CLASSIFYRELATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "CLIENT_CONTROLLER_ALL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "CLIENT_CONTROLLER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "CM_CONF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 150 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ERRORCODE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "EVENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "IMAGECLASSIFY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "OCRINFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "OCR_DETAILS_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 131 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "OCR_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "OPEROBJ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "OUT_INTERFACE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "SCENE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "SOFTUPDATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "SYS_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_AMOUNT_RANGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_APP_SYSTEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_BILL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12540 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_CONFIG_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_DEPART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5850 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_DEPT_ORG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_FLOWCONIFG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_LOGIN_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 721 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_NODE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_PRIVILEGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_ROLE_BILL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_ROLE_DEPART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5681 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_ROLE_MENUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 32 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_SOFTUPDATE_CONTROLLER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_SYS_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 941 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_USERS_ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 183 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "T_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5662 CACHE 10 NOORDER  NOCYCLE ;
CREATE TABLE "ACTIVE_CONF"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"WEBURL" VARCHAR2(128),
	"CMIP" VARCHAR2(20),
	"CMPORT" VARCHAR2(5),
	"YONYOUWEBURL" VARCHAR2(128),
	"COMPRESS" VARCHAR2(4),
	"COMPRESS_RATIO" VARCHAR2(4),
	"SUB_BLACK" VARCHAR2(2),
	"TURN_CORRECT" VARCHAR2(2),
	"RECOGNIZE_OCR" VARCHAR2(2),
	"UPPERTOLOWERCASE" VARCHAR2(2),
	"OTHER_FILE_FORMAT" VARCHAR2(2),
	"COMBINE" VARCHAR2(2),
	"OWERID" NUMBER,
	"COMBINEDIRECTION" VARCHAR2(2),
	"PHONESCANNER" VARCHAR2(2),
	"DOC_DIRECT_TURN_CORRECT" VARCHAR2(2),
	"FILE_ENCRYPT" VARCHAR2(2),
	"MULTI_LABEL" VARCHAR2(2),
	"EXPORT_IMAGE" VARCHAR2(2),
	"APPSCANTIMEOUT" VARCHAR2(16),
	"APPREGISTERTIMEOUT" VARCHAR2(16),
	"INTEGRATE_STYLE" VARCHAR2(32)
) ;
CREATE TABLE "ACTIVE_OWER"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"ORG_ID" VARCHAR2(24),
	"SYSTEMCODE" VARCHAR2(16),
	"DEPTID" VARCHAR2(16),
	"STATUS" VARCHAR2(1),
	"STATUSNAME" VARCHAR2(16),
	"CREATETIME" VARCHAR2(64),
	"CREATEUSER" VARCHAR2(64)
) ;
CREATE TABLE "ACT_GE_BYTEARRAY"
(	"ID_" NVARCHAR2(64),
	"REV_" NUMBER(*,0),
	"NAME_" NVARCHAR2(255),
	"BYTES_" BLOB,
	"GENERATED_" NUMBER(1,0)
) ;
CREATE TABLE "ACT_RE_MODEL"
(	"ID_" NUMBER,
	"OBJID_" NVARCHAR2(255),
	"REV_" NUMBER(*,0),
	"NAME_" NVARCHAR2(255),
	"BILLTYPES_" NVARCHAR2(255),
	"APPSYSTEM_" NVARCHAR2(255),
	"DEPARTS_" NVARCHAR2(255),
	"CATEUSER_" NVARCHAR2(255),
	"CREATE_TIME_" TIMESTAMP (6),
	"LAST_UPDATE_TIME_" TIMESTAMP (6),
	"DEPLOYMENT_TYPE_" VARCHAR2(255),
	"META_INFO_" NVARCHAR2(2000),
	"EDITOR_SOURCE_VALUE_ID_" NVARCHAR2(64),
	"EDITOR_SOURCE_EXTRA_VALUE_ID_" NVARCHAR2(64),
	"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
) ;
CREATE TABLE "ACT_RN_PROCESS"
(	"id_" VARCHAR2(233),
	"nodeid_" VARCHAR2(255),
	"name_" VARCHAR2(255),
	"authority_" VARCHAR2(255),
	"documentatio_" VARCHAR2(2000),
	"previousid_" VARCHAR2(255),
	"nextid_" VARCHAR2(255),
	"modelid_" VARCHAR2(255)
) ;
CREATE TABLE "AMOUNT_RANGE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"AMOUNT_RANGE" VARCHAR2(128),
	"AMOUNT_START" NUMBER,
	"AMOUNT_END" NUMBER
) ;
CREATE TABLE "APPSYSTEM"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"APP_ID" VARCHAR2(64),
	"APP_NAME" VARCHAR2(128),
	"APP_STATUS" VARCHAR2(1),
	"CREATEUSER" VARCHAR2(32),
	"CREATETIME" VARCHAR2(32)
) ;
CREATE TABLE "BILLACCEPTMANAGER"
(	"DEPARTNUM" VARCHAR2(32 CHAR),
	"DEPARTNAME" VARCHAR2(128 CHAR),
	"TEL" VARCHAR2(32 CHAR),
	"USERNUM" VARCHAR2(32 CHAR),
	"USERNAME" VARCHAR2(32 CHAR),
	"ID" VARCHAR2(32 CHAR),
	"USERID" VARCHAR2(32),
	"COMMIT_FLAG" VARCHAR2(4),
	"COMMIT_FLAG_NAME" VARCHAR2(32)
) ;
CREATE TABLE "BILLTASK"
(	"ID" VARCHAR2(32 CHAR),
	"BILL_NO" VARCHAR2(32 CHAR),
	"BILL_DATE" VARCHAR2(32 CHAR),
	"SYSTEM_CODE" VARCHAR2(32 CHAR),
	"SCAN_MAN" VARCHAR2(32 CHAR),
	"SCAN_MAN_NAME" VARCHAR2(32 CHAR),
	"MONEY" VARCHAR2(32 CHAR),
	"BILL_MAN" VARCHAR2(32 CHAR),
	"BILL_MAN_NAME" VARCHAR2(32 CHAR),
	"SCAN_TIME" VARCHAR2(32 CHAR),
	"ATTACH_AMOUNT" VARCHAR2(10 CHAR) DEFAULT null,
	"PASTE_AMOUNT" VARCHAR2(10 CHAR) DEFAULT null,
	"SUBMIT_STATUS" CHAR(10 CHAR) DEFAULT null,
	"SUBMIT_TIME" VARCHAR2(32 CHAR),
	"ACCEPT_MAN" VARCHAR2(32 CHAR),
	"ACCEPT_MAN_NAME" VARCHAR2(32 CHAR),
	"ACCEPT_STATUS" CHAR(10 CHAR),
	"ACCEPT_TIME" VARCHAR2(32 CHAR),
	"PACKAGE_FLAG" CHAR(10 CHAR),
	"PACKAGE_NO" VARCHAR2(64 CHAR),
	"BILL_ORDER" NUMBER(10,0),
	"SUBMIT_STATUS2" VARCHAR2(32 CHAR) DEFAULT null,
	"BILLTYPE" VARCHAR2(32 CHAR),
	"BILLTYPENAME" VARCHAR2(32 CHAR),
	"BUSI_SERIAL_NO" VARCHAR2(32 CHAR),
	"ORGCODE" VARCHAR2(32 CHAR),
	"ORGNAME" VARCHAR2(64 CHAR),
	"BILLSTATUS" VARCHAR2(4 CHAR),
	"BILLSTATUS_NAME" VARCHAR2(64 CHAR),
	"BILL_FLAG" VARCHAR2(4 CHAR),
	"CENTERBILLACCEPTNUM" VARCHAR2(32),
	"CENTERBILLACCEPTNAME" VARCHAR2(32),
	"BILLIDENTRLT" VARCHAR2(4),
	"BILLIDENTRLTNAME" VARCHAR2(32),
	"BILLIDENTRLTP" VARCHAR2(4),
	"BILLIDENTRLTNAMEP" VARCHAR2(32),
	"BHYY" VARCHAR2(512)
) ;
CREATE TABLE "CLASSIFYRELATION"
(	"ID" NUMBER,
	"C_OBJID" VARCHAR2(64),
	"S_OBJID" VARCHAR2(64),
	"B_OBJID" VARCHAR2(64),
	"D_OBJID" VARCHAR2(64),
	"SEQUENCE" VARCHAR2(20)
) ;
CREATE TABLE "CLIENTCONTRAL"
(	"ID" VARCHAR2(255),
	"CLIENT_VERSION" VARCHAR2(255),
	"CLIENT_IP" VARCHAR2(255),
	"CLIENT_MAC" VARCHAR2(255),
	"IFEFFECTIVE" VARCHAR2(255)
) ;
CREATE TABLE "CLIENT_CONTROLLER"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"C_DEPARTNAME" VARCHAR2(32),
	"C_SYSTEMNAME" VARCHAR2(32),
	"C_DEPETNAME" VARCHAR2(32),
	"C_CLIENT_IP" VARCHAR2(32),
	"C_CLIENT_MAC" VARCHAR2(32),
	"C_STATUS" VARCHAR2(1),
	"C_STATUS_NAME" VARCHAR2(32)
) ;
CREATE TABLE "CLIENT_CONTROLLER_ALL"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"C_STATUS" VARCHAR2(1)
) ;
CREATE TABLE "CM_CONF_INFO"
(	"CONIFG_ID" NUMBER(*,0),
	"BRANCH_NO" VARCHAR2(8),
	"CF_KEY" VARCHAR2(36),
	"CF_VALUE" VARCHAR2(36)
) ;
CREATE TABLE "CM_FILE_INFO"
(	"FILE_ID" VARCHAR2(64),
	"CM_VERSION" VARCHAR2(16),
	"CIP" VARCHAR2(32),
	"BATCH_ID" VARCHAR2(64),
	"DOC_DESC" VARCHAR2(128),
	"DOC_NAME" VARCHAR2(128),
	"FILE_NAME" VARCHAR2(516),
	"FILE_FORMAT" VARCHAR2(4),
	"FILE_TYPE" VARCHAR2(2),
	"FILE_SIZE" VARCHAR2(32),
	"REMARK_SIZE" VARCHAR2(32),
	"FILE_MD5" VARCHAR2(64),
	"FILE_SEQ" VARCHAR2(512),
	"OPERATE_STATE" VARCHAR2(2),
	"OPERATE_MSG" VARCHAR2(128),
	"OPERATE_DATE" VARCHAR2(10),
	"OPERATE_TIME" TIMESTAMP (6),
	"FILE_STATE" VARCHAR2(2),
	"SIP" VARCHAR2(32),
	"SPORT" VARCHAR2(8),
	"BACKUP" VARCHAR2(2),
	"STATE" VARCHAR2(2),
	"OCRSTATUS" VARCHAR2(2),
	"CHECKER" VARCHAR2(64),
	"RELATEDFILEID" VARCHAR2(64)
) ;
CREATE TABLE "CM_INFO"
(	"CONTENT_ID" VARCHAR2(32),
	"SYSTEM_CODE" VARCHAR2(32),
	"BRANCH_NO" VARCHAR2(32),
	"USER_NO" VARCHAR2(32),
	"BUSI_SERIAL_NO" VARCHAR2(32),
	"BATCH_ID" VARCHAR2(64),
	"OPERATE_DATE" VARCHAR2(10),
	"OPERATE_TIME" TIMESTAMP (6),
	"TRADE_TYPE" VARCHAR2(2),
	"CLIENT_BATCH_ID" VARCHAR2(64),
	"BACKUP" VARCHAR2(2),
	"UPDATECODE" VARCHAR2(2),
	"BATCHSTATE" VARCHAR2(4),
	"BATCH_TYPE" VARCHAR2(2),
	"ISRELATED" VARCHAR2(2),
	"RELATEDBATCHID" VARCHAR2(64)
) ;
CREATE TABLE "CONFIGPARAM"
(	"ID" VARCHAR2(255),
	"MODETYPE" VARCHAR2(255),
	"CUSTOMIZED_PARAM" VARCHAR2(255)
) ;
CREATE TABLE "CURRENTTASK"
(	"ID" VARCHAR2(32),
	"BILLNUM" VARCHAR2(32),
	"BUSI_SERIAL_NO" VARCHAR2(64),
	"BILLTYPENAME" VARCHAR2(256),
	"CASH" VARCHAR2(256),
	"BILLTYPE" VARCHAR2(256),
	"USER_NO" VARCHAR2(64),
	"DEPARTCODE" VARCHAR2(8),
	"SYSTEMCODE" VARCHAR2(8),
	"MODULENAME" VARCHAR2(32),
	"TASKSTATE" VARCHAR2(32),
	"OBJID" VARCHAR2(48),
	"ORGCODE" VARCHAR2(96),
	"USER_NAME" VARCHAR2(32),
	"BILLDATE" VARCHAR2(64),
	"OCRSTATUS" VARCHAR2(16),
	"TASKSTATENAME" VARCHAR2(64),
	"A_BILLNUM" VARCHAR2(32),
	"SCANTYPE" VARCHAR2(2),
	"SCANTYPENAME" VARCHAR2(16),
	"BILLPAPERFROM" VARCHAR2(2),
	"OPERSUGGEST" VARCHAR2(256),
	"REMARK" VARCHAR2(256),
	"TASKTYPE" VARCHAR2(2),
	"ORGNAME" VARCHAR2(256),
	"TASKTYPENAME" VARCHAR2(64),
	"APPLYTYPE" VARCHAR2(2),
	"SHAREDBATCHES" VARCHAR2(1024),
	"SHARETYPE" VARCHAR2(2),
	"ISRELATED" VARCHAR2(2),
	"PROJECT" VARCHAR2(64),
	"CONTRACT" VARCHAR2(64),
	"PROJECTNAME" VARCHAR2(128),
	"CONTRACTNAME" VARCHAR2(128),
	"BILLSTATENAME" VARCHAR2(16),
	"BILLSTATE" VARCHAR2(2),
	"APPROVALSTATE" VARCHAR2(2),
	"APPROVALSTATENAME" VARCHAR2(1024),
	"STORAGENUM" VARCHAR2(200),
	"CREATETIME" VARCHAR2(30),
	"ISIDENTIFY" VARCHAR2(2) DEFAULT 0,
	"GROUPID" VARCHAR2(64),
	"RELATEDBUSI_SERIAL_NO" VARCHAR2(64),
	"USER_NUM" VARCHAR2(32),
	"PK_BILLTYPE" VARCHAR2(32)
) ;
CREATE TABLE "CUSTOMIZEDPARAM"
(	"ID" VARCHAR2(255),
	"MODETYPE" VARCHAR2(255),
	"CUSTOMIZED_PARAM" VARCHAR2(255)
) ;
CREATE TABLE "ERRORCODE"
(	"ID" NUMBER,
	"ERROR_CODE" VARCHAR2(4),
	"ERROR_CODE_NAME" VARCHAR2(30)
) ;
CREATE TABLE "EVENT"
(	"ID" NUMBER,
	"EVENTNO" VARCHAR2(4),
	"EVENTNAME" VARCHAR2(30),
	"EVENTDATE" VARCHAR2(10),
	"LOGTYPE" NUMBER
) ;
CREATE TABLE "GENERALPARAM"
(	"ID" VARCHAR2(255),
	"PARAM_NUM" VARCHAR2(255),
	"PARAM_TYPE" VARCHAR2(255),
	"DEFAULT" VARCHAR2(255),
	"LENGTH" VARCHAR2(255),
	"RANGE" VARCHAR2(255)
) ;
CREATE TABLE "HISTORYTASK"
(	"ID" VARCHAR2(32),
	"BILLNUM" VARCHAR2(16),
	"BUSI_SERIAL_NO" VARCHAR2(16),
	"DEPART_CODE" VARCHAR2(4),
	"AREA_CODE" VARCHAR2(4),
	"CASH" VARCHAR2(64),
	"BILLTYPE" VARCHAR2(32),
	"BILLSTATE" VARCHAR2(2),
	"USER_NO" VARCHAR2(8),
	"OPERATE_DATE" VARCHAR2(8),
	"OPERATE_TIME" DATE,
	"ORC_ID" VARCHAR2(32)
) ;
CREATE TABLE "IMAGECLASSIFY"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"CATEGORYNAME" VARCHAR2(64),
	"CATEGORYCODE" VARCHAR2(64)
) ;
CREATE TABLE "MOBILE_SCAN"
(	"BSN" VARCHAR2(64),
	"CREATETIME" TIMESTAMP (6),
	"FLAG" NUMBER(*,0),
	"IMEI" VARCHAR2(64)
) ;
CREATE TABLE "MODU"
(	"ID" VARCHAR2(255),
	"MODE_NUM" VARCHAR2(255),
	"MODE_NAME" VARCHAR2(255)
) ;
CREATE TABLE "OCRINFO"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"FILEID" VARCHAR2(64),
	"INVNUM" VARCHAR2(20),
	"INVDATE" VARCHAR2(64),
	"SELLERTAXPAYERNAME" VARCHAR2(1024),
	"SELLERTAXPAYERCODE" VARCHAR2(64),
	"SELLERTAXPAYERADDRANDTEL" VARCHAR2(256),
	"SELLERTAXPAYERACCOUNT" VARCHAR2(256),
	"PASSWD" VARCHAR2(120),
	"SUMAMOUNT" VARCHAR2(64),
	"SUMTAX" VARCHAR2(64),
	"UPPERCASE" VARCHAR2(64),
	"LOWERCASE" VARCHAR2(64),
	"TAXPAYERNAME" VARCHAR2(1024),
	"TAXPAYERCODE" VARCHAR2(64),
	"TAXPAYERADDRANDTEL" VARCHAR2(256),
	"TAXPAYERACCOUNT" VARCHAR2(256),
	"REMARK" VARCHAR2(1024),
	"PAYEE" VARCHAR2(64),
	"REVIEWER" VARCHAR2(64),
	"DRAWER" VARCHAR2(64),
	"PATTEN" VARCHAR2(6),
	"INVCODE" VARCHAR2(20)
) ;
CREATE TABLE "OCR_DETAILS_INFO"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"NAME" VARCHAR2(128),
	"TAX" VARCHAR2(24),
	"RATE" VARCHAR2(10),
	"AMOUNT" VARCHAR2(24),
	"PRICE" VARCHAR2(24),
	"COUNT" VARCHAR2(10),
	"UNIT" VARCHAR2(24),
	"STANDARD" VARCHAR2(256),
	"FILEID" VARCHAR2(64)
) ;
CREATE TABLE "OCR_INFO"
(	"ID" NUMBER,
	"OCR_ID" VARCHAR2(32),
	"OCR_CODE" VARCHAR2(64),
	"OCR_CODE_NAME" VARCHAR2(128),
	"OCR_INFO" VARCHAR2(256),
	"FILE_ID" VARCHAR2(64)
) ;
CREATE TABLE "OPEROBJ"
(	"ID" NUMBER,
	"OPEROBJNO" VARCHAR2(4),
	"OPEROBJNAME" VARCHAR2(30),
	"SCENENO" VARCHAR2(4),
	"OPEROBJDATE" VARCHAR2(10)
) ;
CREATE TABLE "OUT_INTERFACE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"INTERFACENAME" VARCHAR2(64),
	"INTERFACESYSTEMCODE" VARCHAR2(64),
	"INTERFACEURL" VARCHAR2(64),
	"INTERFACEMETHOD" VARCHAR2(64),
	"PARAMTYPE" VARCHAR2(64),
	"PARAMNAME" VARCHAR2(64),
	"PARAMMODEL" VARCHAR2(1024)
) ;
CREATE TABLE "PACKAGELOGS"
(	"ID" VARCHAR2(32),
	"BILL_NO" VARCHAR2(32),
	"ZDMAN" VARCHAR2(32),
	"OPERATINTYPE_NAME" VARCHAR2(1024),
	"OPERATIONNAME" VARCHAR2(32),
	"RESULT" VARCHAR2(32),
	"OPERATIONTIME" VARCHAR2(32),
	"OCCUPIED" VARCHAR2(32),
	"ALLOCCUPIED" VARCHAR2(32)
) ;
CREATE TABLE "PACKAGE_BILLNUMS"
(	"PACKAGENUM" VARCHAR2(64 CHAR),
	"BILLNUM" VARCHAR2(64 CHAR),
	"ACCESSORYCOUNT" VARCHAR2(32 CHAR),
	"PASTELISTCOUNT" VARCHAR2(32 CHAR),
	"ID" VARCHAR2(32 CHAR),
	"ORGNAME" VARCHAR2(32 CHAR)
) ;
CREATE TABLE "PARCELACCEPTMANAGER"
(	"DEPARTNUM" VARCHAR2(32 CHAR),
	"DEPARTNAME" VARCHAR2(128 CHAR),
	"TEL" VARCHAR2(32 CHAR),
	"USERNUM" VARCHAR2(32 CHAR),
	"USERNAME" VARCHAR2(32 CHAR),
	"ID" VARCHAR2(32 CHAR) DEFAULT sys_guid(),
	"USERID" VARCHAR2(32),
	"COMADDRESS" VARCHAR2(128)
) ;
CREATE TABLE "POSTTASK"
(	"ID" VARCHAR2(32 CHAR),
	"PACKAGE_NO" VARCHAR2(64 CHAR),
	"PACKAGE_DATE" VARCHAR2(32 CHAR),
	"PACKAGE_TIME" VARCHAR2(32 CHAR),
	"SYSTEM_CODE" VARCHAR2(32 CHAR),
	"PACKAGE_MAN" VARCHAR2(32 CHAR),
	"PACKAGE_MAN_NAME" VARCHAR2(32 CHAR),
	"BILL_AMOUNT" VARCHAR2(10 CHAR),
	"POST_STATUS" VARCHAR2(10 CHAR),
	"POST_TIME" VARCHAR2(32 CHAR),
	"POST_CODE" VARCHAR2(32 CHAR),
	"SIGN_MAN" VARCHAR2(32 CHAR),
	"SIGN_MAN_NAME" VARCHAR2(32 CHAR),
	"SIGN_TIME" VARCHAR2(32 CHAR),
	"UNPACK" VARCHAR2(10 CHAR),
	"ACCESSORYCOUNT" VARCHAR2(10 CHAR),
	"PASTELISTCOUNT" VARCHAR2(10 CHAR),
	"POST_STATUS_NAME" VARCHAR2(32 CHAR),
	"ORGCODE" VARCHAR2(32 CHAR),
	"ORGNAME" VARCHAR2(64 CHAR),
	"EXPRESS" VARCHAR2(32 CHAR),
	"MAIL_ADDRESS" VARCHAR2(128)
) ;
CREATE TABLE "SCENE"
(	"ID" NUMBER,
	"SCENENO" VARCHAR2(4),
	"SCENENAME" VARCHAR2(30),
	"SCENEDATE" VARCHAR2(10)
) ;
CREATE TABLE "SOFTUPDATE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"FILENAME" VARCHAR2(256),
	"VERSION" VARCHAR2(64),
	"UPDATEINFO" VARCHAR2(2048),
	"FILEPATH" VARCHAR2(256),
	"STATUSNAME" VARCHAR2(64),
	"LEVEL" NUMBER,
	"STATUS" VARCHAR2(64),
	"CREATETIME" VARCHAR2(32),
	"CREATEUSER" VARCHAR2(32)
) ;
CREATE TABLE "SYS_LOG"
(	"ID" NUMBER,
	"EVENTNO" VARCHAR2(4),
	"OPTTIME" VARCHAR2(20),
	"OPTUSER" VARCHAR2(16),
	"OPTDEPART" VARCHAR2(16),
	"OPTARGET" VARCHAR2(50),
	"OPTCONTENT" VARCHAR2(512),
	"OPTRESULT" NUMBER
) ;
CREATE TABLE "SYS_LOG_BAK"
(	"ID" NUMBER,
	"EVENTNO" VARCHAR2(4),
	"OPTTIME" VARCHAR2(20),
	"OPTUSER" VARCHAR2(16),
	"OPTDEPART" VARCHAR2(16),
	"OPTARGET" VARCHAR2(50),
	"OPTCONTENT" VARCHAR2(512),
	"OPTRESULT" NUMBER,
	"IMPORTDATE" VARCHAR2(8)
) ;
CREATE TABLE "T_APP_SYSTEM"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"SYS_ID" VARCHAR2(64),
	"SYS_NAME" VARCHAR2(128),
	"SYS_STATUS" VARCHAR2(1),
	"CREATEUSER" VARCHAR2(64),
	"CREATETIME" VARCHAR2(32),
	"SYS_STATUS_NAME" VARCHAR2(4)
) ;
CREATE TABLE "T_BILL_TYPE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"TYPE_NAME" VARCHAR2(256),
	"TYPE_ID" VARCHAR2(256),
	"PARENTNUM" VARCHAR2(256),
	"ISIDENTIFY" VARCHAR2(2) DEFAULT 0,
	"PK_ORG" VARCHAR2(64),
	"SYSTEM_CODE" VARCHAR2(64),
	"SYSTEM_NAME" VARCHAR2(64),
	"PARENT_SYSTEM" VARCHAR2(64)
) ;
CREATE TABLE "T_CONFIG_LOG"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"USER_ID" VARCHAR2(32),
	"NAME" VARCHAR2(64),
	"SCENE" VARCHAR2(4),
	"OPER_OBJ" VARCHAR2(4),
	"OPER_ACTION" NUMBER,
	"OPER_TIME" VARCHAR2(32),
	"OPER_STATUS" NUMBER,
	"OPER_DESCR" VARCHAR2(2048),
	"CHANNEL" VARCHAR2(32),
	"FOROBJID" VARCHAR2(32)
) ;
CREATE TABLE "T_CONFIG_LOG_BAK"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"USER_ID" VARCHAR2(32),
	"NAME" VARCHAR2(64),
	"SCENE" VARCHAR2(4),
	"OPER_OBJ" VARCHAR2(4),
	"OPER_ACTION" NUMBER,
	"OPER_TIME" VARCHAR2(32),
	"OPER_STATUS" NUMBER,
	"OPER_DESCR" VARCHAR2(2048),
	"CHANNEL" VARCHAR2(32),
	"FOROBJID" VARCHAR2(32),
	"IMPORTDATE" VARCHAR2(8)
) ;
CREATE TABLE "T_DEPART"
(	"ID" NUMBER,
	"DEPARTNUM" VARCHAR2(96),
	"DEPARTNAME" VARCHAR2(256),
	"DEPARTADDRESS" VARCHAR2(32),
	"PARENTNUM" VARCHAR2(96),
	"DEPARTSTATUS" VARCHAR2(2),
	"DEPARTTYPE" VARCHAR2(2),
	"CODE" VARCHAR2(128)
) ;
CREATE TABLE "T_DEPT_ORG"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"DEPT_ID" VARCHAR2(64),
	"DEPT_NAME" VARCHAR2(128),
	"DEPT_STATUS" VARCHAR2(1),
	"DEPT_STATUS_NAME" VARCHAR2(4),
	"CREATEUSER" VARCHAR2(64),
	"CREATETIME" VARCHAR2(32)
) ;
CREATE TABLE "T_FLOWCONIFG"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"PROCESSNAME" VARCHAR2(64),
	"PROCESSID" VARCHAR2(64),
	"AFTERID" VARCHAR2(64),
	"BEFOREID" VARCHAR2(64),
	"PROCESSSTATUS" VARCHAR2(64),
	"PROCESSTYPE" VARCHAR2(64),
	"TASKSTATE" VARCHAR2(2),
	"TASKSTATENAME" VARCHAR2(32)
) ;
CREATE TABLE "T_LOGIN_LOG"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"USER_ID" VARCHAR2(32),
	"NAME" VARCHAR2(64),
	"LOGIN_TIME" VARCHAR2(32),
	"LOGOUT_TIME" VARCHAR2(32),
	"IP" VARCHAR2(32),
	"CHANNEL" VARCHAR2(32)
) ;
CREATE TABLE "T_LOGIN_LOG_BAK"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(32),
	"USER_ID" VARCHAR2(32),
	"NAME" VARCHAR2(64),
	"LOGIN_TIME" VARCHAR2(32),
	"LOGOUT_TIME" VARCHAR2(32),
	"IP" VARCHAR2(32),
	"CHANNEL" VARCHAR2(32),
	"IMPORTDATE" VARCHAR2(8)
) ;
CREATE TABLE "T_MENU"
(	"ID" NUMBER,
	"M_MENUID" NUMBER,
	"M_MENUNAME" VARCHAR2(164),
	"M_ICON" VARCHAR2(3),
	"M_URL" VARCHAR2(128),
	"M_PARENTNUM" VARCHAR2(9),
	"M_LEVEL" VARCHAR2(16),
	"M_TYPE" VARCHAR2(4)
) ;
CREATE TABLE "T_MODULE_PARAM"
(	"ID" NUMBER,
	"MODULENAME1" VARCHAR2(32),
	"MODULENAME2" VARCHAR2(32),
	"MODULEPARAM" VARCHAR2(128)
) ;
CREATE TABLE "T_NODE_DEFINE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(255),
	"NAME" VARCHAR2(255),
	"NODE_NUM" NUMBER,
	"NODE_TYPE" VARCHAR2(2)
) ;
CREATE TABLE "T_PARAM_COMMON"
(	"ID" NUMBER,
	"PARAMKEY" VARCHAR2(32),
	"PARAMVALUE" VARCHAR2(64),
	"PARAMTYPE" VARCHAR2(2),
	"PARAMNAME" VARCHAR2(32),
	"CLASSIFYTYPE" VARCHAR2(32)
) ;
CREATE TABLE "T_PARAM_CUSTOM"
(	"ID" NUMBER,
	"MODULEID" VARCHAR2(32),
	"CUSTOMPARAM" VARCHAR2(128),
	"MODULESTATUS" VARCHAR2(2),
	"CREATOR" VARCHAR2(32),
	"CREATORTIME" VARCHAR2(32),
	"LASTMODIFIER" VARCHAR2(32),
	"LASTMODIFYTIME" VARCHAR2(32)
) ;
CREATE TABLE "T_PRIVILEGE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"P_DEPARTNUM" VARCHAR2(2048),
	"P_BILLTYPE" VARCHAR2(128),
	"P_AMOUNTRANGE" VARCHAR2(128),
	"P1" VARCHAR2(128),
	"P2" VARCHAR2(128),
	"ROLEID" VARCHAR2(64),
	"P_TASKSTATE" VARCHAR2(128)
) ;
CREATE TABLE "T_PRIVILEGE_TYPE"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"TYPE_NAME" VARCHAR2(64)
) ;
CREATE TABLE "T_ROLE"
(	"ID" NUMBER,
	"ROLENUM" VARCHAR2(64),
	"ROLENAME" VARCHAR2(32),
	"ROLESTATUS" VARCHAR2(64),
	"MENULIST" VARCHAR2(64),
	"OPERLIST" VARCHAR2(64),
	"CREATEUSER" VARCHAR2(64),
	"CREATETIME" VARCHAR2(32),
	"ROLESTATUSNAME" VARCHAR2(32)
) ;
CREATE TABLE "T_ROLE_BILL"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"TYPE_ID" VARCHAR2(128),
	"ROLEID" VARCHAR2(64)
) ;
CREATE TABLE "T_ROLE_DEPART"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"P_DEPARTNUM" VARCHAR2(128),
	"ROLEID" VARCHAR2(64)
) ;
CREATE TABLE "T_ROLE_MENUS"
(	"ID" NUMBER,
	"ROLENUM" VARCHAR2(32),
	"MENUNUM" VARCHAR2(32),
	"OBJID" VARCHAR2(32)
) ;
CREATE TABLE "T_ROLE_PRIVILEGES"
(	"ID" NUMBER,
	"ROLE_ID" VARCHAR2(16),
	"PRIVILEGE_ID" VARCHAR2(16)
) ;
CREATE TABLE "T_SYS_LOG"
(	"ID" NUMBER,
	"BUSI_SERIAL_NO" VARCHAR2(32),
	"CHANNEL" VARCHAR2(32),
	"USERNAME" VARCHAR2(32),
	"BILLCODE" VARCHAR2(32),
	"CLKNO" VARCHAR2(32),
	"CLKNAME" VARCHAR2(64),
	"OPTTIME" VARCHAR2(20),
	"TASKTYPE" NUMBER,
	"ERROR_CODE" VARCHAR2(4),
	"ERROR_MESSAGE" VARCHAR2(256)
) ;
CREATE TABLE "T_SYS_LOG_BAK"
(	"ID" NUMBER,
	"BUSI_SERIAL_NO" VARCHAR2(32),
	"CHANNEL" VARCHAR2(32),
	"USERNAME" VARCHAR2(32),
	"BILLCODE" VARCHAR2(32),
	"CLKNO" VARCHAR2(32),
	"CLKNAME" VARCHAR2(64),
	"OPTTIME" VARCHAR2(20),
	"TASKTYPE" NUMBER,
	"ERROR_CODE" VARCHAR2(4),
	"ERROR_MESSAGE" VARCHAR2(256),
	"IMPORTDATE" VARCHAR2(8)
) ;
CREATE TABLE "T_USER"
(	"ID" NUMBER,
	"USERNAME" VARCHAR2(128),
	"USERNUM" VARCHAR2(32),
	"DEPARTNUM" VARCHAR2(48),
	"SEX" VARCHAR2(1),
	"PASSWORD" VARCHAR2(32),
	"TELEPHONENUM" VARCHAR2(12),
	"ADDRESS" VARCHAR2(64),
	"ROLES" VARCHAR2(512),
	"CREATER" VARCHAR2(64),
	"CREATETIME" VARCHAR2(32),
	"CUSTOMPRIVILEGE" VARCHAR2(128),
	"DEFAULTPRIVILEGE" VARCHAR2(64),
	"STATUS" VARCHAR2(32),
	"LASTMODIFYUSER" VARCHAR2(32),
	"LASTMODIFYTIME" VARCHAR2(32),
	"LASTMODIFYREASON" VARCHAR2(32),
	"STATUSNAME" VARCHAR2(32),
	"OBJID" VARCHAR2(64),
	"SYSTEMCODE" VARCHAR2(10)
) ;
CREATE TABLE "T_USERS_ROLES"
(	"ID" NUMBER,
	"OBJID" VARCHAR2(64),
	"USER_OBJID" VARCHAR2(64),
	"ROLE_OBJID" VARCHAR2(64)
) ;


Insert into ACTIVE_CONF (ID,OBJID,WEBURL,CMIP,CMPORT,YONYOUWEBURL,"COMPRESS",COMPRESS_RATIO,SUB_BLACK,TURN_CORRECT,RECOGNIZE_OCR,UPPERTOLOWERCASE,OTHER_FILE_FORMAT,COMBINE,OWERID,COMBINEDIRECTION,PHONESCANNER,DOC_DIRECT_TURN_CORRECT,FILE_ENCRYPT,MULTI_LABEL,EXPORT_IMAGE,APPSCANTIMEOUT,APPREGISTERTIMEOUT,INTEGRATE_STYLE) values (4,'1dc68d4e2547423c8ffb07c91bbeaf8b','http://20.10.80.190:8777/TIMS-Server/services/ContentInfoService','20.10.80.190','28390',null,'1','80','0','0','1','0','1','0',3,'0','1','0','0','1','0','3','5','OEM');

Insert into ACTIVE_OWER (ID,OBJID,ORG_ID,SYSTEMCODE,DEPTID,STATUS,STATUSNAME,CREATETIME,CREATEUSER) values (3,'fa7f5153e63d4231953d23cc90b9db2b','0','0','0','0','已配置','20160819152438','admin');

Insert into AMOUNT_RANGE (ID,OBJID,AMOUNT_RANGE,AMOUNT_START,AMOUNT_END) values (3,'7b7b02c9a51c4fc4ac18f9ac16c800b9','1112.0-1113.0',1112,1113);


Insert into CM_CONF_INFO (CONIFG_ID,BRANCH_NO,CF_KEY,CF_VALUE) values (1,'01','SIP','127.0.0.1');
Insert into CM_CONF_INFO (CONIFG_ID,BRANCH_NO,CF_KEY,CF_VALUE) values (2,'01','SPORT','8777');



Insert into ERRORCODE (ID,ERROR_CODE,ERROR_CODE_NAME) values (1,'0000','成功');
Insert into ERRORCODE (ID,ERROR_CODE,ERROR_CODE_NAME) values (2,'1000','添加失败');
Insert into ERRORCODE (ID,ERROR_CODE,ERROR_CODE_NAME) values (3,'1001','更新失败');
Insert into ERRORCODE (ID,ERROR_CODE,ERROR_CODE_NAME) values (4,'1002','删除失败');
Insert into ERRORCODE (ID,ERROR_CODE,ERROR_CODE_NAME) values (5,'1003','NC调用失败');
Insert into ERRORCODE (ID,ERROR_CODE,ERROR_CODE_NAME) values (6,'1004','任务状态不一致');


Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (41,'0001','用户登录','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (42,'0002','用户退出','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (43,'0003','修改密码','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (44,'0004','用户添加','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (45,'0005','用户修改','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (46,'0006','用户删除','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (47,'0007','用户停用','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (48,'0008','用户启用','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (49,'0009','密码初始化','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (50,'0010','角色添加','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (51,'0011','角色修改','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (52,'0012','角色删除','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (53,'0013','菜单权限分配','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (54,'0014','操作权限分配','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (55,'0015','菜单添加','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (56,'0016','菜单修改','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (57,'0017','菜单删除','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (58,'0018','权限添加','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (59,'0019','权限修改','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (60,'0020','权限删除','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (61,'0021','单据登记','20160601',2);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (62,'0022','单据扫描','20160601',2);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (63,'0023','单据审核','20160601',2);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (64,'0024','单据比对','20160601',2);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (65,'0025','任务录入','20160601',2);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (66,'0026','控件参数','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (67,'0027','机构管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (68,'0028','应用系统管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (69,'0029','部门管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (70,'0030','单据类型管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (71,'0031','金额范围管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (72,'0032','外部接口管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (73,'0033','影像分类管理','20160601',3);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (74,'0034','审批流配置','20160601',6);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (75,'0035','软件升级管理','20160601',7);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (76,'0036','升级控制管理','20160601',7);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (77,'0037','日志导出','20160601',1);
Insert into EVENT (ID,EVENTNO,EVENTNAME,EVENTDATE,LOGTYPE) values (78,'0038','日志导入','20160601',1);




Insert into MOBILE_SCAN (BSN,CREATETIME,FLAG,IMEI) values ('1002A210000000000J79',to_timestamp('30-1月 -18 02.41.28.135036000 下午','DD-MON-RR HH.MI.SS.FF AM'),0,null);
Insert into MOBILE_SCAN (BSN,CREATETIME,FLAG,IMEI) values ('0001A2100000000E8NU2',to_timestamp('30-1月 -18 06.24.19.767048000 下午','DD-MON-RR HH.MI.SS.FF AM'),0,null);
Insert into MOBILE_SCAN (BSN,CREATETIME,FLAG,IMEI) values ('1001A21000000013EHA5',to_timestamp('30-1月 -18 02.42.58.505806000 下午','DD-MON-RR HH.MI.SS.FF AM'),0,null);






Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (1,'1001','用户管理','1000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (2,'1002','角色管理','1000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (3,'1003','功能菜单','1000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (4,'1004','系统日志','1000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (5,'2001','控件参数','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (6,'2002','机构管理','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (7,'2003','应用系统管理','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (8,'2004','部门管理','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (9,'2005','单据类型管理','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (10,'2006','外部接口管理','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (11,'2007','影像分类管理','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (12,'2008','影像分类关联','2000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (13,'3001','登录日志','3000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (14,'3002','配置日志','3000','20160629');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (15,'4001','单据接收人员管理','4000','20180426');
Insert into OPEROBJ (ID,OPEROBJNO,OPEROBJNAME,SCENENO,OPEROBJDATE) values (14,'4002','邮包签收人员管理','4000','20180426');





Insert into SCENE (ID,SCENENO,SCENENAME,SCENEDATE) values (1,'1000','系统管理','20160629');
Insert into SCENE (ID,SCENENO,SCENENAME,SCENEDATE) values (2,'2000','参数管理','20160629');
Insert into SCENE (ID,SCENENO,SCENENAME,SCENEDATE) values (3,'3000','平台日志','20160629');
Insert into SCENE (ID,SCENENO,SCENENAME,SCENEDATE) values (4,'4000','邮包管理','20180426');


Insert into SOFTUPDATE (ID,OBJID,FILENAME,VERSION,UPDATEINFO,FILEPATH,STATUSNAME,"LEVEL",STATUS,CREATETIME,CREATEUSER) values (11,'06a1191306c64362aac7e4c287e0fb51','TIMS-Client3.0.8.2.exe','3.0.8.2','TIMS-Client3.0.8.','D:/20171107softpath/software/3.0.8.2/TIMS-Client3.0.8.2.exe','有效',null,'0','20180115133830','admin');



Insert into T_APP_SYSTEM (ID,OBJID,SYS_ID,SYS_NAME,SYS_STATUS,CREATEUSER,CREATETIME,SYS_STATUS_NAME) values (5,'d90db6df6cb14bf4b83d900011f9e6ea','NC','NC','1','admin','20160524110538','是');


Insert into T_BILL_TYPE (ID,OBJID,TYPE_NAME,TYPE_ID,PARENTNUM,ISIDENTIFY,PK_ORG,SYSTEM_CODE,SYSTEM_NAME,PARENT_SYSTEM) values (1,'07447aafdd4b4471adaf37c9aeb5f37a','票据类型根目录','0','-1','0',null,null,null,null);






Insert into T_DEPART (ID,DEPARTNUM,DEPARTNAME,DEPARTADDRESS,PARENTNUM,DEPARTSTATUS,DEPARTTYPE,CODE) values (1,'0','机构根目录','1','-1','0','-1',null);




Insert into T_FLOWCONIFG (ID,OBJID,PROCESSNAME,PROCESSID,AFTERID,BEFOREID,PROCESSSTATUS,PROCESSTYPE,TASKSTATE,TASKSTATENAME) values (201,'91dc3c7aa0544bb8924c6700ba45f0c7','登记','1','2','0','0','0','0','登记');
Insert into T_FLOWCONIFG (ID,OBJID,PROCESSNAME,PROCESSID,AFTERID,BEFOREID,PROCESSSTATUS,PROCESSTYPE,TASKSTATE,TASKSTATENAME) values (202,'4b47d80150ac447fb78930b2251180b3','扫描','2','999','1','0','2','1','扫描');





Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (21,25,'单据查询','ico','/TIMS-Server/imageManagerController/toBillsQuery.action','0','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (171,33,'影像分类管理','ico','/TIMS-Server/classifyController/classifyList.action','1','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (141,11,'待办任务','ico','/TIMS-Server/imageManagerController/toImageListall.action','0','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (11,22,'机构管理','ico','/TIMS-Server/departController/departList.action','1','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (13,23,'应用系统管理','ico','/TIMS-Server/systemController/systemList.action','1','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (3,0,'影像管理','ico',null,'-1','0',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (4,1,'参数管理','ico',null,'-1','0',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (8,5,'软件管理','ico',null,'-1','0',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (9,6,'平台日志','ico',null,'-1','0',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (58,10,'系统管理','ico',null,'-1','0',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (59,-1,'菜单根目录','ico',null,'-2','-1',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (99,27,'单据类型管理','ico','/TIMS-Server/billTypeController/billList.action','1','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (64,15,'用户管理','ico','/TIMS-Server/userController/userList.action','10','1',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (65,16,'角色管理','ico','/TIMS-Server/roleController/roleList.action','10','1',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (66,17,'功能菜单','ico','/TIMS-Server/menuController/menuList.action','10','1',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (67,18,'日志管理','ico','/TIMS-Server/sysLogController/sysLogList.action','10','1',null);
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (71,20,'控件参数配置','ico','/TIMS-Server/activeParamController/activeControllerList.action','1','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (73,21,'软件升级管理','ico','/TIMS-Server/softController/softUpdate.action','5','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (100,28,'金额范围管理','ico','/TIMS-Server/amountController/amountList.action','1','1','0');
--Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (12,37,'影像分类关联管理','ico','/TIMS-Server/classifyRelateController/queryRelationList.action','1','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (202,39,'登录日志','ico','/TIMS-Server/loginLogController/loginLogList.action','6','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (203,40,'配置日志','ico','/TIMS-Server/configLogController/configLogList.action','6','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (102,43,'邮包管理','ico',null,'-1','0','0');
-- Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (103,44,'票据提交待办','ico','/TIMS-Server/commitBillController/toPage.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (104,45,'票据接收待办','ico','/TIMS-Server/acceptBillController/toList.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (105,46,'邮包管理','ico','/TIMS-Server/postManagerController/listPackage.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (106,47,'邮包签收待办','ico','/TIMS-Server/acceptpackcontroller/listPackage.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (107,48,'纸质票据跟踪','ico','/TIMS-Server/paperBillTrackController/QueryList.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (108,49,'单据接收人员管理','ico','/TIMS-Server/billAcceptManagerController/QueryList.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (109,50,'邮包签收人员管理','ico','/TIMS-Server/parcelAcceptManagerController/QueryList.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (110,51,'共享中心单据签收待办','ico','/TIMS-Server/acceptBillController/CenterbillsList.action','43','1','0');
Insert into T_MENU (ID,M_MENUID,M_MENUNAME,M_ICON,M_URL,M_PARENTNUM,M_LEVEL,M_TYPE) values (120,52,'单据补入','ico','/TIMS-Server/acceptpackcontroller/relistPackage.action','43','1','0');








Insert into T_PRIVILEGE (ID,OBJID,P_DEPARTNUM,P_BILLTYPE,P_AMOUNTRANGE,P1,P2,ROLEID,P_TASKSTATE) values (13,'6927f7a21544412c8d5886415b7a588d',null,null,'[0-*]',null,null,'9de04ea9874f4edfa8a2a1ce3ebe196d','2');
Insert into T_PRIVILEGE (ID,OBJID,P_DEPARTNUM,P_BILLTYPE,P_AMOUNTRANGE,P1,P2,ROLEID,P_TASKSTATE) values (21,'517bc89146d6473b95a1a5e569fd0245',null,null,'[0-*]',null,null,'d2f4e5a8fddc44f6ade173bb1442c36f','0');
Insert into T_PRIVILEGE (ID,OBJID,P_DEPARTNUM,P_BILLTYPE,P_AMOUNTRANGE,P1,P2,ROLEID,P_TASKSTATE) values (22,'9422346220e949739133072bce103776',null,null,'[0-*]',null,null,'bc35221018114158a4e7af8dcf3364df','1');
Insert into T_PRIVILEGE (ID,OBJID,P_DEPARTNUM,P_BILLTYPE,P_AMOUNTRANGE,P1,P2,ROLEID,P_TASKSTATE) values (1,'1fa4c38b0e68471aaf945f26fe56c267',null,null,'[0-*]',null,null,'ea072fcdb569470ebc6206860763aea2','-1');
Insert into T_PRIVILEGE (ID,OBJID,P_DEPARTNUM,P_BILLTYPE,P_AMOUNTRANGE,P1,P2,ROLEID,P_TASKSTATE) values (25,'3275add67a7a49928d74bb58d983b405',null,null,'[0-*]',null,null,'7e37de7295bd4e0996ec2dc2cb65ccd3','0');




Insert into T_ROLE (ID,ROLENUM,ROLENAME,ROLESTATUS,MENULIST,OPERLIST,CREATEUSER,CREATETIME,ROLESTATUSNAME) values (1,'81c210f2b39d472386dc3d2a99ca25ef','超级管理员(admin)','0',null,null,'admin','20160105221615','新建');














Insert into T_USER (ID,USERNAME,USERNUM,DEPARTNUM,SEX,PASSWORD,TELEPHONENUM,ADDRESS,ROLES,CREATER,CREATETIME,CUSTOMPRIVILEGE,DEFAULTPRIVILEGE,STATUS,LASTMODIFYUSER,LASTMODIFYTIME,LASTMODIFYREASON,STATUSNAME,OBJID,SYSTEMCODE) values (1,'admin','admin','1','0','4297f44b13955235245b2497399d7a93','119','天创',null,'admin','20160105221732',null,null,'0','admin','20160222175840',null,'有效','4aff0bc4da994249a14c6afa230360a8',null);


Insert into T_USERS_ROLES (ID,OBJID,USER_OBJID,ROLE_OBJID) values (1,'9128732cd2c4483d8fa9295ed9a1eece','4aff0bc4da994249a14c6afa230360a8','81c210f2b39d472386dc3d2a99ca25ef');

ALTER TABLE "BILLTASK" ADD  COMPARISONRESULT VARCHAR2(64);

ALTER TABLE "BILLTASK" ADD  CHECKRESULT VARCHAR2(64);


ALTER TABLE "T_PARAM_CUSTOM" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_PARAM_CUSTOM" ADD CONSTRAINT "PRIMARYT_PARAM_CUSTOM1" PRIMARY KEY ("ID");

ALTER TABLE "T_ROLE_PRIVILEGES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_ROLE_PRIVILEGES" ADD CONSTRAINT "PRIMARYT_ROLE_PRIVILEGES1" PRIMARY KEY ("ID");

ALTER TABLE "CUSTOMIZEDPARAM" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CUSTOMIZEDPARAM" ADD CONSTRAINT "PRIMARYCUSTOMIZEDPARAM1" PRIMARY KEY ("ID");

ALTER TABLE "T_PRIVILEGE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_PRIVILEGE" ADD CONSTRAINT "PRIMARYT_PRIVILEGE1" PRIMARY KEY ("ID");

ALTER TABLE "HISTORYTASK" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "HISTORYTASK" ADD CONSTRAINT "PRIMARYHISTORYTASK1" PRIMARY KEY ("ID");

ALTER TABLE "T_ROLE_MENUS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_ROLE_MENUS" ADD CONSTRAINT "PRIMARYT_ROLE_MENUS1" PRIMARY KEY ("ID");

ALTER TABLE "CM_INFO" MODIFY ("CONTENT_ID" NOT NULL ENABLE);
ALTER TABLE "CM_INFO" ADD CONSTRAINT "P_CM_INFO_PK" PRIMARY KEY ("CONTENT_ID");

ALTER TABLE "SOFTUPDATE" ADD CONSTRAINT "PRIMARYSOFTUPDATE1" PRIMARY KEY ("ID");

ALTER TABLE "T_USERS_ROLES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_USERS_ROLES" ADD CONSTRAINT "PRIMARYT_USERS_ROLES1" PRIMARY KEY ("ID");

ALTER TABLE "T_USER" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_USER" ADD CONSTRAINT "PRIMARYT_USER1" PRIMARY KEY ("ID");

ALTER TABLE "CLIENTCONTRAL" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CLIENTCONTRAL" ADD CONSTRAINT "PRIMARYCLIENTCONTRAL1" PRIMARY KEY ("ID");

ALTER TABLE "ACT_RN_PROCESS" MODIFY ("id_" NOT NULL ENABLE);
ALTER TABLE "ACT_RN_PROCESS" ADD CONSTRAINT "ACT_RN_PROCESS_PK" PRIMARY KEY ("id_");

ALTER TABLE "GENERALPARAM" ADD CONSTRAINT "PRIMARYGENERALPARAM1" PRIMARY KEY ("ID");

ALTER TABLE "ACT_GE_BYTEARRAY" ADD PRIMARY KEY ("ID_");

ALTER TABLE "ACT_GE_BYTEARRAY" MODIFY ("ID_" NOT NULL ENABLE);
ALTER TABLE "T_ROLE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_ROLE" ADD CONSTRAINT "PRIMARYT_ROLE1" PRIMARY KEY ("ID");

ALTER TABLE "ACTIVE_CONF" ADD CONSTRAINT "PRIMARYACTIVE_CONF1" PRIMARY KEY ("ID");

ALTER TABLE "CM_CONF_INFO" MODIFY ("CONIFG_ID" NOT NULL ENABLE);
ALTER TABLE "CM_CONF_INFO" ADD CONSTRAINT "P_CM_CONF_INFO_PK" PRIMARY KEY ("CONIFG_ID");

ALTER TABLE "OCRINFO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_PARAM_COMMON" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_PARAM_COMMON" ADD CONSTRAINT "PRIMARYT_PARAM_COMMON1" PRIMARY KEY ("ID");

ALTER TABLE "ACT_RE_MODEL" ADD PRIMARY KEY ("ID_");

ALTER TABLE "ACT_RE_MODEL" MODIFY ("OBJID_" NOT NULL ENABLE);
ALTER TABLE "ACT_RE_MODEL" MODIFY ("ID_" NOT NULL ENABLE);
ALTER TABLE "T_NODE_DEFINE" ADD PRIMARY KEY ("ID");

ALTER TABLE "T_NODE_DEFINE" MODIFY ("OBJID" NOT NULL ENABLE);
ALTER TABLE "T_NODE_DEFINE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CURRENTTASK" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CURRENTTASK" ADD CONSTRAINT "PRIMARYCURRENTTASK1" PRIMARY KEY ("ID");

ALTER TABLE "T_MODULE_PARAM" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_MODULE_PARAM" ADD CONSTRAINT "PRIMARYT_MODULE_PARAM1" PRIMARY KEY ("ID");

ALTER TABLE "CM_FILE_INFO" MODIFY ("FILE_ID" NOT NULL ENABLE);
ALTER TABLE "CM_FILE_INFO" ADD CONSTRAINT "P_CM_FILE_INFO_PK" PRIMARY KEY ("FILE_ID");

ALTER TABLE "OCR_DETAILS_INFO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_MENU" ADD CONSTRAINT "PRIMARYT_MENU1" PRIMARY KEY ("ID");

ALTER TABLE "CLASSIFYRELATION" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_DEPART" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "T_DEPART" ADD CONSTRAINT "PRIMARYT_DEPART1" PRIMARY KEY ("ID");

ALTER TABLE "MODU" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "MODU" ADD CONSTRAINT "PRIMARYMODU1" PRIMARY KEY ("ID");

ALTER TABLE "OCR_INFO" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CONFIGPARAM" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CONFIGPARAM" ADD CONSTRAINT "PRIMARYCONFIGPARAM1" PRIMARY KEY ("ID");

ALTER TABLE "ACTIVE_OWER" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "ACTIVE_OWER" ADD CONSTRAINT "PRIMARYACTIVE_OWER1" PRIMARY KEY ("ID");

ALTER TABLE "ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_SOURCE" FOREIGN KEY ("EDITOR_SOURCE_VALUE_ID_")
	  REFERENCES "ACT_GE_BYTEARRAY" ("ID_") ENABLE;
ALTER TABLE "ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_SOURCE_EXTRA" FOREIGN KEY ("EDITOR_SOURCE_EXTRA_VALUE_ID_")
	  REFERENCES "ACT_GE_BYTEARRAY" ("ID_") ENABLE;

CREATE OR REPLACE TRIGGER "ACTIVE_CONF_TRI" BEFORE
INSERT ON ACTIVE_CONF FOR EACH ROW       WHEN (new.ID is null) begin
select ACTIVE_CONF_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "ACTIVE_CONF_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "ACTIVE_OWER_TRI" BEFORE
INSERT ON ACTIVE_OWER FOR EACH ROW      WHEN (new.ID is null) begin
select ACTIVE_OWER_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "ACTIVE_OWER_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "CM_CONFIG_TRI" BEFORE
INSERT ON CM_CONF_INFO FOR EACH ROW       WHEN (new.CONIFG_ID is null) begin
select CM_CONF_SEQ.nextval into :new.CONIFG_ID from dual;
end;
/
ALTER TRIGGER "CM_CONFIG_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "ERRORCODE_TRI" BEFORE
INSERT ON ERRORCODE FOR EACH ROW     WHEN (new.ID is null) begin
select ERRORCODE_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "ERRORCODE_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "EVENT_TRI" BEFORE
INSERT ON EVENT FOR EACH ROW      WHEN (new.ID is null) begin
select EVENT_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "EVENT_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "OCRINFO_TRI" BEFORE
INSERT ON OCRINFO FOR EACH ROW
WHEN (new.ID is null) begin
select OCRINFO_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "OCRINFO_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "OCR_DETAILS_INFO_TRI" BEFORE
INSERT ON OCR_DETAILS_INFO FOR EACH ROW
WHEN (new.ID is null) begin
select OCR_DETAILS_INFO_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "OCR_DETAILS_INFO_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "OCR_INFO_TRI" BEFORE
INSERT ON OCR_INFO FOR EACH ROW      WHEN (new.ID is null) begin
select OCR_INFO_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "OCR_INFO_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "OPEROBJ_TRI" BEFORE
INSERT ON OPEROBJ FOR EACH ROW     WHEN (new.ID is null) begin
select OPEROBJ_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "OPEROBJ_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "SCENE_TRI" BEFORE
INSERT ON SCENE FOR EACH ROW     WHEN (new.ID is null) begin
select SCENE_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "SCENE_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "SOFTUPDATE_TRI" BEFORE
INSERT ON SOFTUPDATE FOR EACH ROW       WHEN (new.ID is null) begin
select SOFTUPDATE_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "SOFTUPDATE_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_APP_SYSTEM_TRI" BEFORE
INSERT ON T_APP_SYSTEM FOR EACH ROW      WHEN (new.ID is null) begin
select T_APP_SYSTEM_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_APP_SYSTEM_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_CONFIG_LOG_TRI" BEFORE
INSERT ON T_CONFIG_LOG FOR EACH ROW     WHEN (new.ID is null) begin
select T_CONFIG_LOG_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_CONFIG_LOG_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_DEPART_TRI" BEFORE
INSERT ON T_DEPART FOR EACH ROW      WHEN (new.ID is null) begin
select T_DEPART_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_DEPART_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_FLOWCONIFG_TRI" BEFORE
INSERT ON T_FLOWCONIFG FOR EACH ROW       WHEN (new.ID is null) begin
select T_FLOWCONIFG_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_FLOWCONIFG_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_LOGIN_LOG_TRI" BEFORE
INSERT ON T_LOGIN_LOG FOR EACH ROW     WHEN (new.ID is null) begin
select T_LOGIN_LOG_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_LOGIN_LOG_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_MENU_TRI" BEFORE
INSERT ON T_MENU FOR EACH ROW      WHEN (new.ID is null) begin
select T_MENU_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_MENU_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_ROLE_BILL_TRI" BEFORE
INSERT ON T_ROLE_BILL FOR EACH ROW       WHEN (new.ID is null) begin
select T_ROLE_BILL_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_ROLE_BILL_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_ROLE_DEPART_TRI" BEFORE
INSERT ON T_ROLE_DEPART FOR EACH ROW       WHEN (new.ID is null) begin
select T_ROLE_DEPART_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_ROLE_DEPART_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_ROLE_TRI" BEFORE
INSERT ON T_ROLE FOR EACH ROW      WHEN (new.ID is null) begin
select T_ROLE_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_ROLE_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_SYS_LOG_TRI" BEFORE
INSERT ON T_SYS_LOG FOR EACH ROW     WHEN (new.ID is null) begin
select T_SYS_LOG_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_SYS_LOG_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_USER_TRI" BEFORE
INSERT ON T_USER FOR EACH ROW      WHEN (new.ID is null) begin
select T_USER_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_USER_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_bill_type_TRI" BEFORE
INSERT ON T_PRIVILEGE_TYPE FOR EACH ROW       WHEN (new.ID is null) begin
select T_bill_type_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_bill_type_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_dept_org_TRI" BEFORE
INSERT ON T_dept_org FOR EACH ROW       WHEN (new.ID is null) begin
select CM_CONF_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_dept_org_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "T_role_menus_TRI" BEFORE
INSERT ON T_role_menus FOR EACH ROW       WHEN (new.ID is null) begin
select T_role_menus_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "T_role_menus_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "amount_range_TRI" BEFORE
INSERT ON amount_range FOR EACH ROW       WHEN (new.ID is null) begin
select amount_range_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "amount_range_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "classifyrelation_TRI" BEFORE
INSERT ON classifyrelation FOR EACH ROW        WHEN (new.ID is null) begin
select classifyrelation_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "classifyrelation_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "client_controller_TRI" BEFORE
INSERT ON client_controller FOR EACH ROW       WHEN (new.ID is null) begin
select client_controller_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "client_controller_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "imageclassify_TRI" BEFORE
INSERT ON imageclassify FOR EACH ROW       WHEN (new.ID is null) begin
select imageclassify_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "imageclassify_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "out_interface_TRI" BEFORE
INSERT ON out_interface FOR EACH ROW       WHEN (new.ID is null) begin
select out_interface_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "out_interface_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "t_bill_type_TRI" BEFORE
INSERT ON t_bill_type FOR EACH ROW      WHEN (new.ID is null) begin
select t_bill_type_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "t_bill_type_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "t_privilege_TRI" BEFORE
INSERT ON t_privilege FOR EACH ROW       WHEN (new.ID is null) begin
select t_privilege_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "t_privilege_TRI" ENABLE;
CREATE OR REPLACE TRIGGER "t_users_roles_TRI" BEFORE
INSERT ON t_users_roles FOR EACH ROW       WHEN (new.ID is null) begin
select  t_users_roles_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "t_users_roles_TRI" ENABLE;

--2018.10.09 解决单据状态同步问题
--任务表currenttask添加字段
alter table currenttask add pk_tradetype varchar2(32);

--凭证联查使用表
create table combine_query (
	id varchar2(64) primary key not null,
	bsns varchar2(4000 byte),
	createtime timestamp default sysdate
);

--影像分类表增加类型字段
alter table imageclassify add boxtype varchar2(32);
--影像分类中间表
create table billtype_classify(
  uuid varchar2(64) primary key not null,
  bill_type_id varchar2(64) not null,
  classify_objid varchar2(64) not null,
  create_time varchar2(32) not null
);
--系统出厂预置一个影像分类
insert into imageclassify (id,objid,categoryname,categorycode,boxtype) values (0,'a8541e198faa4e1089bb1654b4b0c3f7','预置分类1','0','sys');

alter table T_DEPART add NSRSBH varchar2(256);


alter table CURRENTTASK add CODE varchar2(256);
alter table CURRENTTASK add NSRSBH varchar2(256);

--存储税务云查验SaveToken数据，用于提交到税务云
create table save_token (
	uuid varchar2(64) primary key not null,
	bsn varchar2(64),
	invcode varchar2(64),
	invnum varchar2(64),
	submitter varchar2(64),
	datetime varchar2(64),
	token varchar2(64)
);

commit;